task/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', upload_file_view, name='upload-view'),
    path('data', get_data, name='get_data'),
    path('download-csv', d_csv, name='d_csv'),
    path('download-pdf', some_view, name='some_view'),
]

task/task/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/core/models.py
from django.db import models
from django.utils.translation import activate


class Csv(models.Model):
    file_name = models.FileField(upload_to='core')
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)


class Data(models.Model):
    date = models.CharField(max_length=200)
    appl_open = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    appl_high = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    appl_low = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    appl_close = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    appl_volume = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    appl_adjusted = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    dn = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    mavg = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    up = models.DecimalField(max_digits=100, decimal_places=10, blank=True, null=True)
    direction = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    

task/core/forms.py
from django import forms
from .models import *


class CsvModelForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name', )

task/core/views.py
from django.shortcuts import render
from django.utils.translation import activate
from .forms import CsvModelForm
from .models import Csv, Data
import csv
from .utils import get_plot, get_boxplot
import numpy as np
import matplotlib.pyplot as plt
from django.http import HttpResponse, response
from django.core.paginator import EmptyPage, Paginator
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas


def upload_file_view(request):
    form = CsvModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvModelForm
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)

            for i, row in enumerate(reader):
                if i == 0:
                    pass
                else:
                    print(row)  
                    date = row[0]
                    appl_open = row[1]
                    appl_high = row[2]
                    appl_low = row[3]
                    appl_close = row[4]
                    appl_volume = row[5]
                    appl_adjusted = row[6]
                    dn = row[7]
                    mavg = row[8]
                    up = row[9]
                    direction = row[10]

                    Data.objects.create(
                        date = date,
                        appl_open = appl_open,
                        appl_high = appl_high,
                        appl_low = appl_low,
                        appl_close = appl_close,
                        appl_volume = appl_volume,
                        appl_adjusted = appl_adjusted,
                        dn = dn,
                        mavg = mavg,
                        up = up,
                        direction = direction             
                    )
                   
            obj.activated = True
            obj.save()

    return render(request, 'core/task.html', {'form' : form})


def get_data(request):
    dataset = Data.objects.all()
    qs = Data.objects.get_queryset().order_by('id')
    x = [x.appl_low for x in dataset]
    y = [y.appl_high for y in dataset]
    z = [z.appl_open for z in dataset]
    area = 14
    colors = np.random.rand(len(x))
    chart = get_plot(x, y, area, colors)
    data_1 = np.random.normal(x)
    data_2 = np.random.normal(y)
    data_3 = np.random.normal(z)
    data = [data_1, data_2, data_3]
    chart2 = get_boxplot(data)
    p = Paginator(qs, 5)
    page_num = request.GET.get('page', 1)

    try :
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)

    return render(request, 'core/table.html', {'dataset': dataset, 'qs': page, 'chart': chart, 'chart2': chart2})


def d_csv(request):
    dataset = Data.objects.all()
    response = HttpResponse(content_type = 'text/csv')
    response['Content-Disposition'] = 'attachment; filename=data.csv'
    writer = csv.writer(response)

    writer.writerow(['Date', 'aapl_open', 'appl_high', 'appl_low', 'appl_close', 'appl_volume', 'appl_adjusted', 'dn', 'mavg', 'up', 'direction'])

    for data in dataset:
        writer.writerow([data.date, data.appl_open, data.appl_high, data.appl_low, data.appl_close, data.appl_volume, data.appl_adjusted, data.dn, data.mavg, data.up, data.direction ])
    return response


def some_view(request):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)
    x = 5
    p.drawString(100, 100, "{{x}}")
    p.showPage()
    p.save()
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='hello.pdf')

task/core/templates/core/table.html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Show Data</title>
  </head>
  <body>
  <script type="text/javascript">
        $("#btnPrint").live("click", function () {
            var divContents = $("#dvContainer").html();
            var printWindow = window.open('', '', 'height=400,width=800');
            printWindow.document.write('<html><head><title>DIV Contents</title>');
            printWindow.document.write('</head><body >');
            printWindow.document.write(divContents);
            printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();
        });
    </script>

    <script>

    $( document ).ready(function() {
    $('#lnkPrint').click(function()
     {
         window.print();
     });
});
    </script>
  <form style="text-align:center;">

  <a href="#" id="lnkPrint">Print</a>
</form>
  
  <style>
table, th, td{
  border:1px solid black;
}
</style>
<a href="/" class="btn btn-outline-dark" role="button" aria-pressed="true"><i class="bi bi-house"></i> Go to Home</a>
<center>
    <h4 style="color:green"><u><b> Export Data Table </b><u/></h4>
</center>
  <br>
  <a style="float:right;" href="{% url 'core:d_csv' %}" class="btn btn-outline-dark" role="button" aria-pressed="true"> Download CSV File</a>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL High</th>
    </tr>
  </thead>
    {% for q in qs %}
  <tbody>
    <tr>
      <th scope="row">{{q.date}}</th>
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_high}}</td>
    </tr>
  </tbody>

 {% endfor %}
</table>
 <div style="float:right;">
 {% if qs.has_previous %}
  <a href="{% url 'core:get_data' %}?page={{qs.previous_page_number}}">Previous Page</a>
  {% endif %}
    {% if qs.has_next %}
  <a href="{% url 'core:get_data' %}?page={{qs.next_page_number}}">Next Page</a>
  {% endif %}
  </div>
<br>
<br>
<center>

<input style="float:right;" type="button" value="Download PDF File" id="btnPrint" />
 <form id="form1">
    <div id="dvContainer">    
<div class="tabset">
  <input type="radio" name="tabset" id="tab1" aria-controls="marzen" checked>
  <label for="tab1"> Histogram </label>
  <input type="radio" name="tabset" id="tab2" aria-controls="rauchbier">
  <label for="tab2">Scatter Plot</label>
  <input type="radio" name="tabset" id="tab3" aria-controls="dunkles">
  <label for="tab3">Box Plot</label>
    
  <div class="tab-panels">
    <section id="marzen" class="tab-panel">
      <div class="chartBox">
  <canvas id="histogram"></canvas>
</div>
  </section>
    <section id="rauchbier" class="tab-panel">
      <div>
{% if chart %}
    <img src="data:image/png;base64, {{ chart|safe }}"
    {% endif %}
</div>
    </section>
    <section id="dunkles" class="tab-panel">
     <div>
{% if chart2 %}
    <img src="data:image/png;base64, {{ chart2|safe }}"
    {% endif %}
</div>
    </section>
  </div>
  
</div>
    

</center>



<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <style>

            /*
            CSS for the main interaction
            */
            .tabset > input[type="radio"] {
            position: absolute;
            left: -200vw;
            }

            .tabset .tab-panel {
            display: none;
            }

            .tabset > input:first-child:checked ~ .tab-panels > .tab-panel:first-child,
            .tabset > input:nth-child(3):checked ~ .tab-panels > .tab-panel:nth-child(2),
            .tabset > input:nth-child(5):checked ~ .tab-panels > .tab-panel:nth-child(3),
            .tabset > input:nth-child(7):checked ~ .tab-panels > .tab-panel:nth-child(4),
            .tabset > input:nth-child(9):checked ~ .tab-panels > .tab-panel:nth-child(5),
            .tabset > input:nth-child(11):checked ~ .tab-panels > .tab-panel:nth-child(6) {
            display: block;
            }

            /*
            Styling
            */
            body {
            font: 16px/1.5em "Overpass", "Open Sans", Helvetica, sans-serif;
            color: #333;
            font-weight: 300;
            }

            .tabset > label {
            position: relative;
            display: inline-block;
            padding: 15px 15px 25px;
            border: 1px solid transparent;
            border-bottom: 0;
            cursor: pointer;
            font-weight: 600;
            }

            .tabset > label::after {
            content: "";
            position: absolute;
            left: 15px;
            bottom: 10px;
            width: 22px;
            height: 4px;
            background: #8d8d8d;
            }

            .tabset > label:hover,
            .tabset > input:focus + label {
            color: #06c;
            }

            .tabset > label:hover::after,
            .tabset > input:focus + label::after,
            .tabset > input:checked + label::after {
            background: #06c;
            }

            .tabset > input:checked + label {
            border-color: #ccc;
            border-bottom: 1px solid #fff;
            margin-bottom: -1px;
            }

            .tab-panel {
            padding: 30px 0;
            border-top: 1px solid #ccc;
            }

            /*
            Demo purposes only
            */
            *,
            *:before,
            *:after {
            box-sizing: border-box;
            }

            body {
            padding: 30px;
            }

            .tabset {
            max-width: 65em;
            }

            .chartBox {
                width: 900px;
                height: 500px;
            }

            </style>

            <script>
            const ctx = document.getElementById('histogram').getContext('2d');

            const chart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for data in dataset %} {{ data.id }}, {% endfor %}],
                datasets: [{
                label: 'AAPL High',
                data: [{% for data in dataset %} {{ data.appl_high }}, {% endfor %}],
                backgroundColor: 'green',
                borderWidth: 0,
                barPercentage: 1,
                categoryPercentage: 1
                }]
            },
            options: {
                scales: {
                xAxes: [{
                    display: false,
                    barPercentage: 1,
                    ticks: {
                    max: 3,
                    }

                }, {
                    display: true,
                    ticks: {
                    autoSkip: false,
                    max: 4,
                    }
                }],
                yAxes: [{
                    ticks: {
                    beginAtZero: true
                    }
                }]
                }
            }
            });

            </script> 


</div>
    
    </form>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

task/core/templates/core/task.html
{% extends 'base.html' %} 

{% block title %}
2
{% endblock title %}

{% block content %}
<br>
<br>

<form action="" method="POST" id="form" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <br>
    <br>
    <button type="submit" class="ui secondary button"><i class="cloud icon"></i> Upload</button>
</form>
<br>
<br>
<br>
<br>
<center>
<button class="ui right labeled icon button">
  <i class="right arrow icon"></i>
  <a href="data">Show Data
</button>
</center>
{% comment %} 
<script>

    const form = document.getElementById('form')
    form.addEventListener("submit", submitHandler)

    function submitHandler(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: window.location.pathname,
            data: $("#form").serializer(),
            contentType:false,
            mimeType: 'multipart/form-data',
            dataType: 'json',
            success: function(data) {
                if (data.msg == 'Success'){
                    alert('Form is Submitted');
                }
            }
        })
    }

</script> {% endcomment %}




{% endblock content %}

task/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <title>Task - {% block title %}{% endblock title %}</title>

  </head>
  <body>
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>